queue_rules:
  - name: Default merge queue
    autoqueue: true
    draft_bot_account: harishmaddali
    merge_bot_account: harishmaddali
    update_bot_account: harishmaddali
    merge_method: merge
    merge_conditions:
      - or:
          - check-success=Run pgTAP database tests
          - check-skipped=Run pgTAP database tests
merge_queue:
  max_parallel_checks: 10
merge_protections:
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 10"
merge_protections_settings:
  reporting_method: check-runs
